### ISSUE TITLE
Director Global zone is created even if disabled

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icinga-powershell-framework#294]
Hi, 

I installed agent all over the environment with -addDirectorGlobal is set to 0 and I expected it to be not added on all hosts. 
 
## Expected Behavior
Director Global Zone wont be added

## Current Behavior
Director Global Zone is added

## Your Environment
* PowerShell Version used (`$PSVersionTable.PSVersion`): 5.1

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`): Windows 2019

**Comment by LordHepipud** [comment]
Hello,

thanks for the issue. Which version of Icinga for Windows are you using and how is the install wizard executed?
The global zones are only added of explicitly set by the arguments, otherwise they are not configured.

This used to be an issue, but was fixed with v1.3.1: #188 

Could you please share on how you run the installation?

**Comment by mkayontour** [comment]
I don't find anything how to check the installed version in the documentation: https://icinga.com/docs/icinga-for-windows/latest/doc/frameworkusage/06-Update-Framework-And-Components/

But we don't have the newest version available I guess.

**Comment by mkayontour** [comment]
We updated the version and it now works, I just opened the issue cause I haven't seen a issue regarding this yet.

**Comment by LordHepipud** [comment]
Hello,

you can do it with this:

```powershell
Get-Module -Name icinga-powershell-framework
```
