### ISSUE TITLE
Hostname override in Start-IcingaAgentInstallWizard leads to signing problem when registering a new host

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga-powershell-framework#324]
Start-IcingaAgentInstallWizard -Hostname "testtest" ...
## Expected Behavior
certificate should be signed

## Current Behavior

wrong hostname for ticket request

problem in:
https://github.com/Icinga/icinga-powershell-framework/blob/482af353c8665a89a5b455ae09775bc57d0f7b14/lib/core/icingaagent/misc/Start-IcingaAgentDirectorWizard.psm1#L95

## Possible Solution
set hostname in Start-IcingaAgentDirectorWizard.psm1

[Start-IcingaAgentDirectorWizard.psm1.txt](https://github.com/Icinga/icinga-powershell-framework/files/6967981/Start-IcingaAgentDirectorWizard.psm1.txt)
[Start-IcingaAgentInstallWizard.psm1.txt](https://github.com/Icinga/icinga-powershell-framework/files/6967982/Start-IcingaAgentInstallWizard.psm1.txt)

## Steps to Reproduce (for bugs)
1) have no hostnameNOT1 and hostname1 in icinga director
on hostname1:
2) have icinga-powershell-framework installed and loaded
3) Start-IcingaAgentInstallWizard -SelfServiceAPIKey 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -UseDirectorSelfService 1 -DirectorUrl 'https://icinga.domain.at/icingaweb2/director/' -OverrideDirectorVars 0 -ConvertEndpointIPConfig 1 -Ticket '' -EmptyTicket 1 -InstallFrameworkPlugins 0 -EmptyCA 1 -RunInstaller  -Hostname hostnameNOT1 -AutoUseFQDN 0 -AutoUseHostname 0  

## Your Environment
Windows 10 
Framework 1.5.0
Director 1.8.1

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.

Actually this is not a bug and by design enforced by the Icinga Director. The way on how the host is registered within the Icinga Director is defined within the Self Service API configuration. These values are used for the creation.

To change this behavior, you need to set to `-OverrideDirectorVars 1` and follow the wizard, changing the values there. This will then ensure you can override the behavior from the local machine.

**Comment by LordHepipud** [comment]
Would it be possible to test the current master of the Icinga PowerShell Framework, and instead of the old wizard, use

```powershell
icinga -Manage
```

This will be the new future installation method which should be able to handle this problems just fine.

Once the Management Console is open, hit the following menus

* [0] Installation
* [0] New configuration
* [3] Icinga Director Self-Service API
* Enter the URL or your Icinga Director
* Enter your Self-Service API key
* [2] Hostname -> change the value you want there
* [4] DirectorRegisterHost

You can then modify advanced properties with `a` or simply hit enter to reach the installation menu for installation.

**Comment by moreamazingnick** [comment]
i tried out todays master, but there is no option of overriding the hostname to a completely differerent value. is such a thing planed in the future or should we stick to a workaround ?
Thanks for your help,

best regards 
Nicolas

**Comment by LordHepipud** [comment]
You want to change the hostname entirely of the system? This is currently not supported by neither the old wizard nor the new IMC implementation.

May I ask why you not simply change the hostname of Windows?

In addition you could also set a display name in Icinga Web 2, to have a different name on the frontend. But the object name should match the hostname of the machine in general.

**Comment by moreamazingnick** [comment]
Client A has a full dedicated self installed root server and sets the fqdn to host.hisdomain.local. the maschine should be in the icinga inventory and as host.exampledomain.com. I know that changeing the displayname is the better solution but not really an option
