### ISSUE TITLE
Own check fail if name does not start with invoke-icinga

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga-powershell-framework#359]
as mentioned in https://community.icinga.com/t/own-checks-downt-work-since-i-installed-new-agent-on-windows/7845/8
own checks fail if the name does not start with invoke-icinga.

## Expected Behavior
check should execute 

## Current Behavior
own checks fail if name differs from invoke-icinga*
manual checks failed with newer powershell framework (this worked before)

## Possible Solution
https://github.com/Icinga/icinga-powershell-framework/blob/bbbc6ee8e95e6bdd5dcdf76447de3d3a7a634b2e/lib/icinga/plugin/New-IcingaCheckBaseObject.psm1#L22
use a more generic way 

or

https://github.com/Icinga/icinga-powershell-framework/blob/bbbc6ee8e95e6bdd5dcdf76447de3d3a7a634b2e/lib/icinga/plugin/New-IcingaCheckBaseObject.psm1#L29
replace return with $this.__CheckCommand = "Generic_Icinga_Check";

## Steps to Reproduce (for bugs)
1) write own check Invoke-MyIcingaCheckXYZ
2) use-icinga
3) Invoke-MyIcingaCheckXYZ
or:
1) $check= New-IcingaCheck -Name "Check" -Value 1
2) $check.CritIfLowerThan(2)
3) New-IcingaCheckresult -Check $check-Compile
fails because there is no checkcommand

Error:
Ausnahme beim Aufrufen von "Compile" mit 0 Argument(en):  "Es ist nicht möglich, einen Index auf ein NULL-Array anzuwenden."
In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache\framework_cache.psm1:20871 Zeichen:16
return $IcingaCheckResult.Compile();
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ScriptMethodRuntimeException

## Context
It should be possible to execute a check manually without inside a psm1 file
It should be possible to execute a checkcommand with a different name 

## Your Environment
Windows 10
Powershell 5
framework 1.5.2 -1.6

Best regard
Nicolas

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. This is not a bug, as it is by designed created this way.

The naming `Invoke-IcingaCheck` is used as internal `namespace` for ensuring we are inside a plugin context. This also is used for automatically creating the configuration files for Icinga 2 and the Icinga Director.

We also mentiond this topic inside the [plugin developer guide](https://icinga.com/docs/icinga-for-windows/latest/doc/developerguide/11-Custom-Plugins/#create-a-new-plugin).

By enforcing this naming policy, we can assure an easier to develop plugin because no other rules have to be followed in general.

Everything else would make the development much more complicated.

**Comment by moreamazingnick** [comment]
but is it by design, that we cant run a check directly like:

$check= New-IcingaCheck -Name "Check" -Value 1
$check.CritIfLowerThan(2)
New-IcingaCheckresult -Check $check -Compile

best regards

**Comment by LordHepipud** [comment]
Nope, that should work. Fixed that - thank you :)
