### ISSUE TITLE
Update-IcingaServiceUser freezes for 20 mins

### ISSUE THREAD

**Issue by bibbs** [Icinga/icinga-powershell-framework#394]
Hi, 
when issuing the command `Install-IcingaComponent -name [service|agent]` I am reproducibly experiencing a significant "freeze" within the subsequently called `Update-IcingaServiceUser` --> `Get-IcingaWindowsInformation` at the following line:

`DEBUG: 24948+              >>>> $CimData = (Get-CimInstance @Arguments -ErrorAction Stop)`

After about _21 mins of waiting_ execution always continues without any issues.

The involved call stack is as follows
`Get-CimInstance`
`	Get-IcingaWindowsInformation (line 58)`
`		Test-IcingaManagedUser (line 15)`
`			Update-IcingaServiceUser (line 9)`
`				Install-IcingaComponent -name service (line 264)`		
				
While looking at the `Install-IcingaComponent`'s code, I am unsure If `Update-IcingaServiceUser` is needed in section "service", since the ServiceUser is already set before within the previous called `Install-IcingaforWindowsService`'s return clause - without such issue ... ?

Despite seeing my install script successfully completing it feels hard to accept these 40 mins when installing `Service` + `Agent` ...

my Environment:
IcingaforWindows Framework1.6.1
WindowsPowershell  5.1.14393
Windows Server 2016

**Comment by LordHepipud** [comment]
Hello,

Thank you for the issue. In general, this call is sadly required because on how the MSI installer itself works.
The reason the call takes very long, is because the users are fetched to check if the user assigned is managed by Icinga for Windows (which is required in some cases by managing JEA).

We will provide an update to this, mitigating the error in case JEA is not used on the systems.

In case JEA is used, we will move to another method to fetch user information, which is only supported starting with .NET Framework 5.1.

The problem in this case is proably that a huge Active Directory is behind, causing the WMI query to take very long in certain environments, because instead of just local users, all AD users are fetched.

The new command `Get-LocalUser` is only available, in case .NET Framework and PowerShell 5.1 are installed and would fail by default on Windows 2012 R2 or older.

**Comment by LordHepipud** [comment]
Could you please test the linked PR? This should resolve the problem

**Comment by bibbs** [comment]
I've tested with master from 2022-01-19 (after this got merged into)
The problem is gone! Thank you.
(as you guessed, my Active Directory is indeed VERY large)

BTW, concerning "testing" - are there any "snapshot" builds of the framework or plugins? I couldn't find any, neither in https://packages.icinga.com/IcingaForWindows/snapshot/ nor any snapshot-tagged ones in the stable repo.
I manually copied current git into my Modules-directory - is that the right procedure to test pre-release?

**Comment by LordHepipud** [comment]
Thank you for the update and the feedback. Yes there is: https://packages.icinga.com/IcingaForWindows/

At the bottom you will find an example to add repositories from GitHub as snapshot and directly install a certain branch as snapshot for testing.

In this example, `$Project` would have been `icinga-powershell-framework` and `$Branch` would have been `fix/managed_user_lookup_time`

I hope this helps in the future!

**Comment by bibbs** [comment]
Ah, that's great! I must admit that I missed this section of the readme part.

Previously when I was exploring the folder "snapshot" with my web browser I only found this "master" which obviously isn't up to date. But actually, as you turned out now, there are all github branches rendered as repos, but all hidden when browsing there! Phenomenal!

Maybe it would be helpful for others to unhide these folders, or just place another copy of that important "readme" just there in the snapshot folder.
Thanks!

**Comment by LordHepipud** [comment]
Sounds like a great idea. I will discuss that internally.
