### ISSUE TITLE
Optimize-IcingaForWindowsMemory causes high load

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga-powershell-framework#491]
#405 fixed a memory leak (thanks!) by calling [Optimize-IcingaForWindowsMemory](https://github.com/Icinga/icinga-powershell-framework/blob/v1.8.0/lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1#L81) for each accepted REST API connection. This effectively means for each HTTP request, because in most scenarios a client sends only one request per connection.

Sadly `Optimize-IcingaForWindowsMemory` seems to be expensive. Wrapping it in `Measure-Command`
```powershell
$ts = Measure-Command { Optimize-IcingaForWindowsMemory -ClearErrorStack; }
Write-IcingaConsolePlain -Message '{0}: Optimize-IcingaForWindowsMemory took {1}s' -Objects (Get-Date -Format HH:mm:ss.fff), $ts.TotalSeconds;
```
reveals execution times of 0.5s on our 2 core virtual machine (varying, but at same magnitude).
```
16:49:04.928: Optimize-IcingaForWindowsMemory took 0.4907853s
```
And so `Optimize-IcingaForWindowsMemory` may well take more time than the actual measurement. For a reference, `Get-WmiObject` takes 0.3s on the same host.

@LordHepipud Can you confirm this? Our affected machines had undergone hardening measures where it's difficult to estimate impact. However, if confirmed, I'd offer to help in finding an improvement.

**Comment by LordHepipud** [comment]
Thank you for the issue. I would have to run some tests, but in general the assumption would be correct that it takes some time to cleanup the memory. We did a lot of improvements, to ensure the memory cleanup is done after each executed task.

So here is what happens:
* Before the listener for a new connection starts, the garbage collection is forced
* Once a new connection attempt is made, Icinga for Windows will proceed with the task
* Once the data is send back to the client as result, we call the garbage collection for the thread in which the request was handled
* Before we accept a new connection, the garbage collection is called again, ensuring the memory on the listener thread is cleaned up

But I agree, if you are heavily utilizing the API, each connection attempt will require a memory cleanup call for the moment. The rest threads itself are fine, because they will cleanup the memory once the execution is done and will not impact the actual responsiveness of the API, as you could spawn more worker threads.

I think a valid and best approach would be, to not call the garbage connection for every connection attempt, but after a certain amount of connections was processed. This would mean one connection attempt will take longer to process, while all others will just work fine.

**Comment by LordHepipud** [comment]
Can you please test the linked PR for this? I made a change that every 50 connection attempts the memory will receive a GC instead for every single one

**Comment by haxtibal** [comment]
> if you are heavily utilizing the API, each connection attempt will require a memory cleanup call for the moment

Heavily using the API is the new default, is it?😉 Because of #131.

> will not impact the actual responsiveness of the API, as you could spawn more worker threads.

Yes, they will have impact. From [.net Fundamentals of garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals): "Before a garbage collection starts, all managed threads are suspended except for the thread that triggered the garbage collection". Thus, `[System.GC]::Collect` called from a worker thread will implicitly suspend all other worker threads and the listener thread.

> I think a valid and best approach would be, to not call the garbage connection for every connection attempt, but after a certain amount of connections was processed. This would mean one connection attempt will take longer to process, while all others will just work fine.

That improves the situation.

Otoh, I'm curious why we have to call `[System.GC]::Collect` at all. I know there's a [user report](http://www.jhouseconsulting.com/2017/09/25/addressing-the-powershell-garbage-collection-bug-1825) about a bug in PowerShell, is that the sole reason? That inofficial bug aside, the garbage collector should magically do it's work and keep the managed heap below some threshold, unless we've unintentionally created long living references to objects that are reachable from [static fields, local variables on a thread's stack, CPU registers, GC handles, finalize queue]. But in that case, the garbage collector can't help, even if manually triggered.

**Comment by LordHepipud** [comment]
The problem is, that on older Windows and PowerShell versions, the memory consumption will go through the roof if we do not call `[System.GC]::Collect` ourselves. Even though this bug is not "official", removing it from the code will cause memory to explode.

The worker threads itself will not be suspended as far as I am concerned regarding my testing. I could run many different queues in parallel, accessing the API, not having to worry about memory or CPU utilization. The performance improvement to the CPU are of course way better now, as GC is only done once in a while and not for every connection attempt like before.

Meanwhile the threads handling the request will still cleanup the memory after each approach. Not doing so will cause a memory leak again.

**Comment by haxtibal** [comment]
> on older Windows and PowerShell versions

Do you know these versions by your own trials? If it's a workaround for some specific PS version, can we make it conditional on that PS version? Or just bump [PowerShellVersion](https://github.com/Icinga/icinga-powershell-framework/blob/v1.8.0/icinga-powershell-framework.psd1#L9) in the manifest? I mean, having a non working GC in a GC collected language is such a terrible bug that it renders the runtime unusable, IMO.

> The worker threads itself will not be suspended as far as I am concerned regarding my testing.

When the GC collects, it compacts memory (defragmentation) an corrects remaining pointers. This is done for the whole managed heap of the whole process, not for a single thread. How do they achieve to not cause races if threads aren't be suspended?

**Comment by LordHepipud** [comment]
I did some personal tests but also had lots of customer environments, suffering from this problem.
I'm right now testing certain other ways, to improve this method entirely.

**Comment by LordHepipud** [comment]
I updated the linked PR with a newer version, which removes all `Optimize-IcingaForWindowsMemory` calls and moves one call into the background daemon, which is executed every 5 minutes.

However, in my opinion and test environment, the memory usage can become quite excessively high between GC collections.

I would appreciate some tests in this matter. CPU usage is of course way better now.

**Comment by haxtibal** [comment]
> I updated the linked PR with a newer version, which removes all `Optimize-IcingaForWindowsMemory` calls and moves one call into the background daemon, which is executed every 5 minutes.

Thanks! Nice approach, imo.

> However, in my opinion and test environment, the memory usage can become quite excessively high between GC collections.

According to [Conditions for a garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#conditions-for-a-garbage-collection), the GC shall only collect in one of these three conditions
- system has low physical memory
- managed heap surpasses acceptable threshold
- `GC.Collect` is called

So the main question is, what "acceptable threshold" happens to be on your test system and CLR. It's complicated to understand how [defaults are derived](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector), and values are automatically adjusted during runtime. My guess is that this can be large (some 100MBs, or even GBs). Then watching your heap grow to that range is not necessarily a leak, but may just be a matter of GC configuration.

Have you already ruled out such a "works as designed" scenario?

> I would appreciate some tests in this matter. CPU usage is of course way better now.

Will try to test and do some profiling, but can't promise when I get to it.

**Comment by haxtibal** [comment]
Just stumbled upon some reads worth sharing
- [Low-memory setup](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Low-memory-setup)
- [High performance setup](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/High-performance-setup-he-IL)

They deal with how to tune the garbage collector by setting `$Env:DOTNET_*` variables when starting a .net application like the `powershell.exe` host.

This seems promising. I could first reproduce something that looks like a leak, and then by changing some of the variables the behavior was gone. Will update here once I understand this better.

**Comment by LordHepipud** [comment]
I'm still evaluating everything, but for the moment, it doesn't look very good.

![oom](https://user-images.githubusercontent.com/5050288/159006527-c02b6960-455d-459b-80fd-72cc602764dd.png)

**Comment by haxtibal** [comment]
> I'm still evaluating everything, but for the moment, it doesn't look very good.

I couldn't reproduce such an error. Memory consumption doesn't look leaky so far, but I have nor long term results neither multiple environments.

Would you consider #497 (in combination with your PR)? While not its primary purpose, it might have an effect on memory consumption too.

**Comment by LordHepipud** [comment]
I think I tracked down some issues there and make other minor changes to other areas as well.
For the PR: I wouldn't mind in general. I will do a change to that later on, because I'm going to add housekeeping on certain internal threads to detect if they are frozen or not.

Those threads will then get terminated and restarted. But this is something you could work into your PR as well by rebasing it later on.

**Comment by LordHepipud** [comment]
So I run some tests with the last implementation and had memory to climb to almost 2GB after several days.
I now made another adjustment, by adding `-SmartGC` flag to the optimize memory function. What it will do, is to check if we are within a custom PowerShell session (thread) and skip the function for 30 attempts. After the 30 attempt, the entire memory - like before - will get force flushed from the session.

This will ensure we do not have to deal with any sort of timer or other delays and certain scenarios, but ensure the PowerShell session will receive a force flush eventually at some point, while not hurting the CPU intensively.

**Comment by haxtibal** [comment]
> What it will do, is to check if we are within a custom PowerShell session (thread)

This indicates one would have to call `Collect` or `GetTotalMemory('forcefullcollection')` from a specific PS session to be effective. That's confusing. All our PS sessions run as the same OS process and share one common managed heap. The garbage collector is implemented at CLR level, and is not aware of such a thing like PS Runspaces. Then, why would a GC call be bound to our sessions (threads)? Is there MS documentation that gives insight? If not this indeed seems like a PS bug.

**Comment by LordHepipud** [comment]
I did some testing with your script and this is not the cause of the memory leak. It just works fine and starts to hang round 32 MB memory.

I'm still digging into several different aspects on when the memory consumption will increase over time, but it is a long term task.

From my point of view, I would go with the current optimisation and start to keep improving with the upcoming releases

**Comment by haxtibal** [comment]
> From my point of view, I would go with the current optimisation and start to keep improving with the upcoming releases

Thanks a lot, #494 is good enough to consider this issue as fixed.

> but it is a long term task

Let me know if I can help.

Btw., #497 now includes your thread house keeping feature. We already use #497 in production, it's up and running smooth for a week and safes quite some CPU load. Maybe you want to give it a try.

**Comment by LordHepipud** [comment]
Both sounds good for me. I have one note added to your PR. If you could add the changelog I posted, I will merge the PR.

Thank you for the input!
