### ISSUE TITLE
Use FQDN instead of IP for host address

### ISSUE THREAD

**Issue by dawidjttf** [Icinga/icinga-powershell-framework#544]
Hello,

Is it possible to use FQDN or hostname instead of IP address for **Host address** ? Right now the script embeds the host IP address and it starts be an issue for us when the workstation moves from one network to another and its IP changes, making the service checks not being able to reach the host.

![image](https://user-images.githubusercontent.com/83832853/185156284-033a7b67-f1b0-4ca3-9784-77f4c1d7cf0e.png)

Thanks!

**Comment by LordHepipud** [comment]
Hello,

thank you for the issue. Fetching the FQDN for a specific host has been more challenging in the past than fetching an IP address, because complex environments will make it impossible to ensure that the FQDN locally fetched is acutally the one reachable from the monitoring.
In addition best practices for monitoring is in general to use an IP-Address instead of FQDN, because in case of DNS failures or problems, the address might not be resolveable and causing different problems.

I would suggest trying to use the Icinga Director and Import-/Sync-Rules to update the hosts with the correct FQDN either from CMDB, Active Directory or DNS services. By doing it this way, the dynamic approach doesn't matter and the initial address will always be overwritten with the correct, current address.

**Comment by dawidjttf** [comment]
Thanks for explaining @LordHepipud, going with host imports from AD sounds reasonable and is something we'll have to look into. Before we get that implemented, I was thinking to 'patch' it on our end to use FQDNs instead of IP but I am not sure in which file we would need to do the change, is there a chance you could you point me to it?

Thanks!

**Comment by mkayontour** [comment]
Is it possible to define the address at the self service installation, we have a problem if the first interface is the wrong IP.

**Comment by LordHepipud** [comment]
It is not yet possible to define the IP-Address for the host during the installation process manually.
In most cases, the hosts were added inside the Icinga Director and some automation tasks updated the IP frequently.

I could make this configurable, but the script has to be changed everytime for each host then.

Thoughts on this?
