### ISSUE TITLE
Icinga for windows only installs framework "1.9.2" an not "1.10.0"

### ISSUE THREAD

**Issue by Murkel71** [Icinga/icinga-powershell-framework#576]
Hello all,

I have been waiting a long time for Framework 1.10.0.
But when I try to install the new framework, the script only installs the 1.9.2 version.
I have taken the script from the documentation.

[Net.ServicePointManager]::SecurityProtocol = ‘tls12, tls11’;
$ProgressPreference = ‘SilentlyContinue’;
[string]$ScriptFile = ‘C:\Users\Public\IcingaForWindows.ps1’;

Invoke-WebRequest -UseBasicParsing
-Uri ‘https://packages.icinga.com/IcingaForWindows/IcingaForWindows.ps1’ `
-OutFile $ScriptFile;

& $ScriptFile -IcingaReposytory 'https://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json'
-ModuleDirectory 'C:\Program Files\WindowsPowerShell\Modules' -AllowUpdate
-SkipWizard;

Install-Icinga -InstallCommand ‘{“IfW-DirectorSelfServiceKey”:{“Values”:[“xxxxxxxxxxxxxxxxxxx”]},“IfW-DirectorUrl”:{“Values”:[“xxxxxxxxxxxxxx/icingaweb2/director”]}}’;

Install-IcingaComponent -Name ‘service’ -Confirm;
Install-IcingaComponent -Name ‘plugins’ -Confirm;

I have tried this several times and only get 1.9.2 installed.

**Comment by wp-perc** [comment]
The same goes for me.
On a fresh installation, I noticed the version is 1.9.2.
Before adding anything (namely, the plugins), I tried to update and got a really ugly error.

![image](https://user-images.githubusercontent.com/47447882/188407578-298035e8-2f11-4678-a8ce-69a071259c8f.png)

The error continues way over the screenshot.

Maybe the two things are related?

**Comment by Marci24h** [comment]
Hi,

I'm having the same issue while deploying on a new machine.
![5696768e19caa4eebaa6ba2874f9a1c507dd6250](https://user-images.githubusercontent.com/43334930/188424040-38c75c07-9db6-4d45-a94f-ec08fed1eb85.png)
On our webserver (custom repository) I saw the initial script downloading the 1.9.2 (old/previous) framework version (/icingastable/framework/icinga-powershell-framework-1.9.2.zip).
![6e21ac83d0353449a9d3a5ca49a86661ac6cedda](https://user-images.githubusercontent.com/43334930/188424060-ddb5b735-01ad-4ef9-894a-68e67e3cd259.png)

But the new version is contained in the repository json (/icingastable/ifw.repo.json).
`grep "1.10.0" /var/www/icingarepo/icingastable/ifw.repo.json`
>
                                           "Location":  "framework\\icinga-powershell-framework-1.10.0.zip",
                                           "Version":  "1.10.0",
                                         "Location":  "plugins\\icinga-powershell-plugins-1.10.0.zip",
                                         "Version":  "1.10.0",

After a short research i found the root cause, the initial PowerShell Script "[IcingaForWindows.ps1](https://packages.icinga.com/IcingaForWindows/IcingaForWindows.ps1)" does a sort operation over a data object from type string.
That results in a wrong Version Order. Version "1.10.0" is before 1.5.0 (at the bottom) and not at the top.
![46d4a9107a29dc2ed406d3e35a83504b3b700ebd](https://user-images.githubusercontent.com/43334930/188424098-80de7e1c-51be-436f-a441-63f3b0075501.png)

for me changing thouse two lines solved the issue.

```
#$KickstartPackage = $RepoData.Packages.Kickstart | Sort-Object Version -Descending | Select-Object -First 1;
#$FrameworkPackage = $RepoData.Packages.Framework | Sort-Object Version -Descending | Select-Object -First 1;
```

```
$KickstartPackage = $RepoData.Packages.Kickstart | Sort-Object -Property {[version[]]$_.Version} -Descending | Select-Object -First 1;
$FrameworkPackage = $RepoData.Packages.Framework | Sort-Object -Property {[version[]]$_.Version} -Descending | Select-Object -First 1;
```

(afterword uploaded to our internal repository location)

There is a very similar topic in the icinga community forum.
[https://community.icinga.com/t/the-required-module-icinga-powershell-framework-with-version-1-10-0-is-not-loaded/10461/2](https://community.icinga.com/t/the-required-module-icinga-powershell-framework-with-version-1-10-0-is-not-loaded/10461?u=marci)

Best Regards,
Marcel

**Comment by LordHepipud** [comment]
Hello,

thanks for the iossue. Have you read the [upgrading docs](https://icinga.com/docs/icinga-for-windows/latest/doc/100-General/01-Upgrading/) before upgrading to v1.10.0? There is a special upgrade path to ensure the framework does not break.

If you already upgraded, please have a look on [IWKB000014](https://icinga.com/docs/icinga-for-windows/latest/doc/knowledgebase/IWKB000014/)

**Comment by LordHepipud** [comment]
Oh wait, there is a problem with the sort function on the kickstarter? I will check that - I misread the issue.

**Comment by Marci24h** [comment]
> Hello,
> 
> thanks for the iossue. Have you read the [upgrading docs](https://icinga.com/docs/icinga-for-windows/latest/doc/100-General/01-Upgrading/) before upgrading to v1.10.0? There is a special upgrade path to ensure the framework does not break.
> 
> If you already upgraded, please have a look on [IWKB000014](https://icinga.com/docs/icinga-for-windows/latest/doc/knowledgebase/IWKB000014/)

yes sure, i read them ;)
until today we used the old deprecated icinga powershell module.
we want to replace this with the new icinga framework and tried to start with 1.9.2 / 1.10.0

**Comment by Marci24h** [comment]
> Oh wait, there is a problem with the sort function on the kickstarter? I will check that - I misread the issue.

yes i think so, no problem

**Comment by LordHepipud** [comment]
I created a PR to fix the sorting issue: https://github.com/Icinga/packages.icinga.com/pull/34

Sorry for the inconvenience.

**Comment by Murkel71** [comment]
Hello all,

I think I have found the error.
In the file "ifw.repo.json" the new version 1.10.0 is in the wrong place.
Shouldn't this be under 1.9.2?

".....   
  "framework": [
                                       {
                                           "Hash": "5477049F71AA1C610E48DC5BAD67CA4C84ED92E7F0591F9CFA5BF1901B7C4B24",
                                           "location": "framework\inga-powershell-framework-1.10.0.zip",
                                           "RelativePath": true,
                                           "version": "1.10.0",
                                           "snapshot": false,
                                           "architecture": "multi"
                                       },
                                       {
                                           "Hash": "570ED8E9F0AECD6A0F4C688EFD50F1B85CC7FC08E7F1A0973D48386B2EB2BF4D",
                                           "location": "framework\inga-powershell-framework-1.5.0.zip",
                                           "RelativePath": true,
                                           "version": "1.5.0",
                                           "snapshot": false,
                                           "architecture": "multi"
                                       },
.....
I will build my own repository and then do an installation.

Translated with www.DeepL.com/Translator (free version)
